### ISSUE TITLE
Cannot open "bin\html5/obj/webfont/nokiafc22.ttf" for writing, do you have correct access permissions?

### ISSUE THREAD

**Issue by RichardBray** [johndimi/djFlixel#13]
For some reason, I get this issue when running the demo in this repo locally.

![Screenshot 2020-11-03 at 15 06 00](https://user-images.githubusercontent.com/1377253/98003000-2081e780-1de6-11eb-8839-01585c2fa813.png)

I'm not sure if it's something to do with my local setup or the demo file in the repo?

I'm testing this on a Mac BTW 😄

**Comment by johndimi** [comment]
Weird. HTML 5 compiles on my Windows setup. 
 - Haxe 4.1.3
 - Flixel 4.8.1
 - Lime 7.8.0
 - OpenFL 8.9.7

I know I haven't updated my libs in a while. Perhaps a newer version of one of these libs breaks it.
The file `nokiefcc2.ttf` is part of the Flixel Library perhaps that one is the culprit?
Try building and testing to FLASH or HASHLINK or even native CPP?
The HTML5 port does not work well for the demo (slowdowns, minor text issues) , and I was not focusing on HTML5 when creating the lib. I have only tested Flash and Hashlink 😅

**Comment by RichardBray** [comment]
Thanks for taking the time to respond @johndimi I'll test it out on Flash, I feel like Hashlink doesn't work as well on Macs for OpenFL projects so I might look into getting some of these features working for HTML5. 

Although looks like someone has already got the menu working in HTML5 https://pncet.itch.io/sawshimi

**Comment by johndimi** [comment]
OK I'm sorry I can't be of any meaningful help.
The FlxMenu indeed works for HTML5, it is just some FX classes (that do pixel read/write) that are off. Nice to see games out there using this. 😊 If you can isolate using just the FLXMENU on a project you can do something I'm sure.
